src/Entity/Parts/AssociationType.php
<?php
/*
 * This file is part of Part-DB (https://github.com/Part-DB/Part-DB-symfony).
 *
 *  Copyright (C) 2019 - 2023 Jan Böhmer (https://github.com/jbtronics)
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as published
 *  by the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

declare(strict_types=1);


namespace App\Entity\Parts;

/**
 * The values of this enums are used to describe how two parts are associated with each other.
 */
enum AssociationType: int
{
    /** A user definable association type, which can be described in the comment field */
    case OTHER = 0;
    /** The owning part is compatible with the other part  */
    case COMPATIBLE = 1;
    /** The owning part supersedes the other part (owner is newer version) */
    case SUPERSEDES = 2;

    /**
     * Returns the translation key for this association type.
     * @return string
     */
    public function getTranslationKey(): string
    {
        return 'part_association.type.' . strtolower($this->name);
    }
}

src/Entity/Parts/Category.php
<?php
/**
 * This file is part of Part-DB (https://github.com/Part-DB/Part-DB-symfony).
 *
 * Copyright (C) 2019 - 2022 Jan Böhmer (https://github.com/jbtronics)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

declare(strict_types=1);

namespace App\Entity\Parts;

use Doctrine\Common\Collections\Criteria;
use ApiPlatform\Doctrine\Common\Filter\DateFilterInterface;
use ApiPlatform\Doctrine\Orm\Filter\DateFilter;
use ApiPlatform\Doctrine\Orm\Filter\OrderFilter;
use ApiPlatform\Metadata\ApiFilter;
use ApiPlatform\Metadata\ApiProperty;
use ApiPlatform\Metadata\ApiResource;
use ApiPlatform\Metadata\Delete;
use ApiPlatform\Metadata\Get;
use ApiPlatform\Metadata\GetCollection;
use ApiPlatform\Metadata\Link;
use ApiPlatform\Metadata\Patch;
use ApiPlatform\Metadata\Post;
use ApiPlatform\OpenApi\Model\Operation;
use ApiPlatform\Serializer\Filter\PropertyFilter;
use App\ApiPlatform\Filter\LikeFilter;
use App\Entity\Attachments\Attachment;
use App\Entity\EDA\EDACategoryInfo;
use App\Repository\Parts\CategoryRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\Common\Collections\ArrayCollection;
use App\Entity\Attachments\CategoryAttachment;
use App\Entity\Base\AbstractPartsContainingDBElement;
use App\Entity\Base\AbstractStructuralDBElement;
use App\Entity\Parameters\CategoryParameter;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * This entity describes a category, a part can belong to, which is used to group parts by their function.
 *
 * @extends AbstractPartsContainingDBElement<CategoryAttachment, CategoryParameter>
 */
#[ORM\Entity(repositoryClass: CategoryRepository::class)]
#[ORM\Table(name: '`categories`')]
#[ORM\Index(columns: ['name'], name: 'category_idx_name')]
#[ORM\Index(columns: ['parent_id', 'name'], name: 'category_idx_parent_name')]
#[ApiResource(
    operations: [
        new Get(security: 'is_granted("read", object)'),
        new GetCollection(security: 'is_granted("@categories.read")'),
        new Post(securityPostDenormalize: 'is_granted("create", object)'),
        new Patch(security: 'is_granted("edit", object)'),
        new Delete(security: 'is_granted("delete", object)'),
    ],
    normalizationContext: ['groups' => ['category:read', 'api:basic:read'], 'openapi_definition_name' => 'Read'],
    denormalizationContext: ['groups' => ['category:write', 'api:basic:write', 'attachment:write', 'parameter:write'], 'openapi_definition_name' => 'Write'],
)]
#[ApiResource(
    uriTemplate: '/categories/{id}/children.{_format}',
    operations: [
        new GetCollection(
            openapi: new Operation(summary: 'Retrieves the children elements of a category.'),
            security: 'is_granted("@categories.read")'
        )
    ],
    uriVariables: [
        'id' => new Link(fromProperty: 'children', fromClass: Category::class)
    ],
    normalizationContext: ['groups' => ['category:read', 'api:basic:read'], 'openapi_definition_name' => 'Read']
)]
#[ApiFilter(PropertyFilter::class)]
#[ApiFilter(LikeFilter::class, properties: ["name", "comment"])]
#[ApiFilter(DateFilter::class, strategy: DateFilterInterface::EXCLUDE_NULL)]
#[ApiFilter(OrderFilter::class, properties: ['name', 'id', 'addedDate', 'lastModified'])]
class Category extends AbstractPartsContainingDBElement
{
    #[ORM\OneToMany(mappedBy: 'parent', targetEntity: self::class)]
    #[ORM\OrderBy(['name' => Criteria::ASC])]
    protected Collection $children;

    #[ORM\ManyToOne(targetEntity: self::class, inversedBy: 'children')]
    #[ORM\JoinColumn(name: 'parent_id')]
    #[Groups(['category:read', 'category:write'])]
    #[ApiProperty(readableLink: false, writableLink: false)]
    protected ?AbstractStructuralDBElement $parent = null;

    #[Groups(['category:read', 'category:write'])]
    protected string $comment = '';

    /**
     * @var string The hint which is shown as hint under the partname field, when a part is created in this category.
     */
    #[Groups(['full', 'import', 'category:read', 'category:write'])]
    #[ORM\Column(type: Types::TEXT)]
    protected string $partname_hint = '';

    /**
     * @var string The regular expression which is used to validate the partname of a part in this category.
     */
    #[Groups(['full', 'import', 'category:read', 'category:write'])]
    #[ORM\Column(type: Types::TEXT)]
    protected string $partname_regex = '';

    /**
     * @var string The prefix for ipn generation for created parts in this category.
     */
    #[Groups(['full', 'import', 'category:read', 'category:write'])]
    #[ORM\Column(type: Types::STRING, length: 255, nullable: false, options: ['default' => ''])]
    protected string $part_ipn_prefix = '';

    /**
     * @var bool Set to true, if the footprints should be disabled for parts this category (not implemented yet).
     */
    #[Groups(['full', 'import', 'category:read', 'category:write'])]
    #[ORM\Column(type: Types::BOOLEAN)]
    protected bool $disable_footprints = false;

    /**
     * @var bool Set to true, if the manufacturers should be disabled for parts this category (not implemented yet).
     */
    #[Groups(['full', 'import', 'category:read', 'category:write'])]
    #[ORM\Column(type: Types::BOOLEAN)]
    protected bool $disable_manufacturers = false;

    /**
     * @var bool Set to true, if the autodatasheets should be disabled for parts this category (not implemented yet).
     */
    #[Groups(['full', 'import', 'category:read', 'category:write'])]
    #[ORM\Column(type: Types::BOOLEAN)]
    protected bool $disable_autodatasheets = false;

    /**
     * @var bool Set to true, if the properties should be disabled for parts this category (not implemented yet).
     */
    #[Groups(['full', 'import', 'category:read', 'category:write'])]
    #[ORM\Column(type: Types::BOOLEAN)]
    protected bool $disable_properties = false;

    /**
     * @var string The default description for parts in this category.
     */
    #[Groups(['full', 'import', 'category:read', 'category:write'])]
    #[ORM\Column(type: Types::TEXT)]
    protected string $default_description = '';

    /**
     * @var string The default comment for parts in this category.
     */
    #[Groups(['full', 'import', 'category:read', 'category:write'])]
    #[ORM\Column(type: Types::TEXT)]
    protected string $default_comment = '';

    /**
     * @var Collection<int, CategoryAttachment>
     */
    #[Assert\Valid]
    #[Groups(['full', 'category:read', 'category:write'])]
    #[ORM\OneToMany(mappedBy: 'element', targetEntity: CategoryAttachment::class, cascade: ['persist', 'remove'], orphanRemoval: true)]
    #[ORM\OrderBy(['name' => Criteria::ASC])]
    protected Collection $attachments;

    #[ORM\ManyToOne(targetEntity: CategoryAttachment::class)]
    #[ORM\JoinColumn(name: 'id_preview_attachment', onDelete: 'SET NULL')]
    #[Groups(['category:read', 'category:write'])]
    protected ?Attachment $master_picture_attachment = null;

    /** @var Collection<int, CategoryParameter>
     */
    #[Assert\Valid]
    #[Groups(['full', 'category:read', 'category:write'])]
    #[ORM\OneToMany(mappedBy: 'element', targetEntity: CategoryParameter::class, cascade: ['persist', 'remove'], orphanRemoval: true)]
    #[ORM\OrderBy(['group' => Criteria::ASC, 'name' => 'ASC'])]
    protected Collection $parameters;

    #[Groups(['category:read'])]
    protected ?\DateTimeImmutable $addedDate = null;
    #[Groups(['category:read'])]
    protected ?\DateTimeImmutable $lastModified = null;

    #[Assert\Valid]
    #[ORM\Embedded(class: EDACategoryInfo::class)]
    #[Groups(['full', 'category:read', 'category:write'])]
    protected EDACategoryInfo $eda_info;

    public function __construct()
    {
        parent::__construct();
        $this->children = new ArrayCollection();
        $this->attachments = new ArrayCollection();
        $this->parameters = new ArrayCollection();
        $this->eda_info = new EDACategoryInfo();
    }

    public function getPartnameHint(): string
    {
        return $this->partname_hint;
    }

    public function setPartnameHint(string $partname_hint): self
    {
        $this->partname_hint = $partname_hint;

        return $this;
    }

    public function getPartnameRegex(): string
    {
        return $this->partname_regex;
    }

    public function setPartnameRegex(string $partname_regex): self
    {
        $this->partname_regex = $partname_regex;

        return $this;
    }

    public function getPartIpnPrefix(): string
    {
        return $this->part_ipn_prefix;
    }

    public function setPartIpnPrefix(string $part_ipn_prefix): void
    {
        $this->part_ipn_prefix = $part_ipn_prefix;
    }

    public function isDisableFootprints(): bool
    {
        return $this->disable_footprints;
    }

    public function setDisableFootprints(bool $disable_footprints): self
    {
        $this->disable_footprints = $disable_footprints;

        return $this;
    }

    public function isDisableManufacturers(): bool
    {
        return $this->disable_manufacturers;
    }

    public function setDisableManufacturers(bool $disable_manufacturers): self
    {
        $this->disable_manufacturers = $disable_manufacturers;

        return $this;
    }

    public function isDisableAutodatasheets(): bool

src/Entity/Parts/PartTraits/AdvancedPropertyTrait.php
<?php
/**
 * This file is part of Part-DB (https://github.com/Part-DB/Part-DB-symfony).
 *
 * Copyright (C) 2019 - 2022 Jan Böhmer (https://github.com/jbtronics)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

declare(strict_types=1);

namespace App\Entity\Parts\PartTraits;

use App\Entity\Parts\InfoProviderReference;
use App\Entity\Parts\PartCustomState;
use Doctrine\DBAL\Types\Types;
use App\Entity\Parts\Part;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Constraints\Length;
use App\Validator\Constraints\UniquePartIpnConstraint;

/**
 * Advanced properties of a part, not related to a more specific group.
 */
trait AdvancedPropertyTrait
{
    /**
     * @var bool Determines if this part entry needs review (for example, because it is work in progress)
     */
    #[Groups(['extended', 'full', 'import', 'part:read', 'part:write'])]
    #[ORM\Column(type: Types::BOOLEAN)]
    protected bool $needs_review = false;

    /**
     * @var string A comma separated list of tags, associated with the part
     */
    #[Groups(['extended', 'full', 'import', 'part:read', 'part:write'])]
    #[ORM\Column(type: Types::TEXT)]
    protected string $tags = '';

    /**
     * @var float|null How much a single part unit weighs in grams
     */
    #[Assert\PositiveOrZero]
    #[Groups(['extended', 'full', 'import', 'part:read', 'part:write'])]
    #[ORM\Column(type: Types::FLOAT, nullable: true)]
    protected ?float $mass = null;

    /**
     * @var string|null The internal part number of the part
     */
    #[Assert\Length(max: 100)]
    #[Groups(['extended', 'full', 'import', 'part:read', 'part:write'])]
    #[ORM\Column(type: Types::STRING, length: 100, nullable: true)]
    #[Length(max: 100)]
    #[UniquePartIpnConstraint]
    protected ?string $ipn = null;

    /**
     * @var InfoProviderReference The reference to the info provider, that provided the information about this part
     */
    #[ORM\Embedded(class: InfoProviderReference::class, columnPrefix: 'provider_reference_')]
    #[Groups(['full', 'part:read'])]
    protected InfoProviderReference $providerReference;

    /**
     * @var ?PartCustomState the custom state for the part
     */
    #[Groups(['extended', 'full', 'import', 'part:read', 'part:write'])]
    #[ORM\ManyToOne(targetEntity: PartCustomState::class)]
    #[ORM\JoinColumn(name: 'id_part_custom_state')]
    protected ?PartCustomState $partCustomState = null;

    /**
     * Checks if this part is marked, for that it needs further review.
     */
    public function isNeedsReview(): bool
    {
        return $this->needs_review;
    }

    /**
     * Sets the "needs review" status of this part.
     *
     * @param bool $needs_review The new status
     *
     * @return Part|self
     */
    public function setNeedsReview(bool $needs_review): self
    {
        $this->needs_review = $needs_review;

        return $this;
    }

    /**
     * Gets a comma separated list, of tags, that are assigned to this part.
     */
    public function getTags(): string
    {
        return $this->tags;
    }

    /**
     * Sets a comma separated list of tags, that are assigned to this part.
     *
     * @param string $tags The new tags
     *
     * @return $this
     */
    public function setTags(string $tags): self
    {
        $this->tags = $tags;

        return $this;
    }

    /**
     * Returns the mass of a single part unit.
     * Returns null, if the mass is unknown/not set yet.
     */
    public function getMass(): ?float
    {
        return $this->mass;
    }

    /**
     * Sets the mass of a single part unit.
     * Sett to null, if the mass is unknown.
     *
     * @param float|null $mass the new mass
     *
     * @return $this
     */
    public function setMass(?float $mass): self
    {
        $this->mass = $mass;

        return $this;
    }

    /**
     * Returns the internal part number of the part.
     * @return string
     */
    public function getIpn(): ?string
    {
        return $this->ipn;
    }

    /**
     * Sets the internal part number of the part
     * @param  string  $ipn The new IPN of the part
     */
    public function setIpn(?string $ipn): Part
    {
        $this->ipn = $ipn;
        return $this;
    }

    /**
     * Returns the reference to the info provider, that provided the information about this part.
     * @return InfoProviderReference
     */
    public function getProviderReference(): InfoProviderReference
    {
        return $this->providerReference;
    }

    /**
     * Sets the reference to the info provider, that provided the information about this part.
     * @param  InfoProviderReference  $providerReference
     * @return Part
     */
    public function setProviderReference(InfoProviderReference $providerReference): Part
    {
        $this->providerReference = $providerReference;
        return $this;
    }

    /**
     * Gets the custom part state for the part
     * Returns null if no specific part state is set.
     */
    public function getPartCustomState(): ?PartCustomState
    {
        return $this->partCustomState;
    }

    /**
     * Sets the custom part state.
     *
     * @return $this
     */
    public function setPartCustomState(?PartCustomState $partCustomState): self
    {
        $this->partCustomState = $partCustomState;

        return $this;
    }
}

templates/parts/edit/_advanced.html.twig
{{ form_row(form.needsReview) }}
{{ form_row(form.favorite) }}
{{ form_row(form.mass) }}
<div {{ stimulus_controller('elements/ipn_suggestion', {
    partId: part.id,
    partCategoryId: part.category ? part.category.id : null,
    partDescription: part.description,
    suggestions: ipnSuggestions,
    'commonSectionHeader': 'part.edit.tab.advanced.ipn.commonSectionHeader'|trans,
    'partIncrementHeader': 'part.edit.tab.advanced.ipn.partIncrementHeader'|trans,
    'suggestUrl': url('ipn_suggestions')
}) }}>
    {{ form_row(form.ipn) }}
</div>
{{ form_row(form.partUnit) }}
{{ form_row(form.partCustomState) }}

templates/parts/edit/_associated_parts.html.twig
{% form_theme form with ['parts/edit/edit_form_styles.html.twig'] %}
{% import 'components/collection_type.macro.html.twig' as collection %}

<div {{ collection.controller(form.associated_parts_as_owner, 'part_association.edit.delete.confirm') }}>
    <table class="table table-striped table-sm" id="association_table" {{ collection.target() }}>
        <tbody>
        {% for assoc in form.associated_parts_as_owner %}
            {{ form_widget(assoc) }}
        {% endfor %}
        </tbody>
    </table>

    <button type="button" class="btn btn-success" {{ collection.create_btn() }}
            {% if not is_granted('edit', part) %}disabled{% endif %}>
        <i class="fas fa-plus-square fa-fw"></i>
        {% trans %}part_lot.create{% endtrans %}
    </button>
</div>

templates/parts/edit/_attachments.html.twig
{% import "components/attachments.macro.html.twig" as attachments %}

{{ form_row(form.master_picture_attachment) }}

{{ attachments.attachment_edit_list(form.attachments) }}

templates/parts/edit/_eda.html.twig
{{ form_row(form.eda_info.reference_prefix) }}
{{ form_row(form.eda_info.value) }}

<div class="row">
    <div class="col-sm-9 offset-sm-3">
        {{ form_row(form.eda_info.visibility) }}
    </div>
</div>

<div class="row mb-2">
    <div class="col-sm-9 offset-sm-3">
        {{ form_widget(form.eda_info.exclude_from_bom) }}
        {{ form_widget(form.eda_info.exclude_from_board) }}
        {{ form_widget(form.eda_info.exclude_from_sim) }}
    </div>
</div>

<div class="row">
    <div class="col-sm-9 offset-sm-3">
        <h6>{% trans %}eda_info.kicad_section.title{% endtrans %}:</h6>
    </div>
</div>
{{ form_row(form.eda_info.kicad_symbol) }}
{{ form_row(form.eda_info.kicad_footprint) }}

templates/parts/edit/_lots.html.twig
{% form_theme form with ['parts/edit/edit_form_styles.html.twig'] %}
{% import 'components/collection_type.macro.html.twig' as collection %}

<div {{ collection.controller(form.partLots, 'part_lot.edit.delete.confirm') }}>
    <table class="table table-striped table-sm" id="lots_table" {{ collection.target() }}>
        <tbody>
        {% for lot in form.partLots %}
            {{ form_widget(lot) }}
        {% endfor %}
        </tbody>
    </table>

    <button type="button" class="btn btn-success" {{ collection.create_btn() }}
            {% if not is_granted('edit', part) %}disabled{% endif %}>
        <i class="fas fa-plus-square fa-fw"></i>
        {% trans %}part_lot.create{% endtrans %}
    </button>
</div>

templates/parts/edit/_main.html.twig
{{ form_row(form.name) }}
{% if part.category is not null and part.category.partnameHint is not empty %}
    <div class="row">
        <div class="col-sm-9 offset-sm-3">
            <p class="form-text help-text"><b>{% trans %}part.edit.name.category_hint{% endtrans %}:</b> {{ part.category.partnameHint }}</p>
        </div>
    </div>
{% endif %}
{{ form_row(form.description) }}
{{ form_row(form.category) }}
{{ form_row(form.tags) }}
{{ form_row(form.minAmount) }}
{{ form_row(form.orderAmount) }}
{{ form_row(form.orderDelivery) }}

{{ form_row(form.footprint) }}

templates/parts/edit/_manufacturer.html.twig
{{ form_row(form.manufacturer) }}
{{ form_row(form.manufacturer_product_number) }}
{{ form_row(form.manufacturer_product_url)}}
{{ form_row(form.manufacturing_status) }}

templates/parts/edit/_orderdetails.html.twig
{# Leave this template at bootstrap 4 for now, as it otherwise destroys our layout #}
{% form_theme form.orderdetails with ['parts/edit/edit_form_styles.html.twig', "bootstrap_5_layout.html.twig"] %}
{% import 'components/collection_type.macro.html.twig' as collection %}

<div {{ collection.controller(form.orderdetails, 'orderdetails.edit.delete.confirm') }}>
    <table class="table table-striped table-sm table-responsive-md" id="orderdetails_table" {{ collection.target() }}>
        <tbody>
        {% for detail in form.orderdetails %}
            {{ form_widget(detail) }}
        {% endfor %}
        </tbody>
    </table>

    <button type="button" class="btn btn-success" {{ collection.create_btn() }}>
        <i class="fas fa-plus-square fa-fw"></i>
        {% trans %}orderdetail.create{% endtrans %}
    </button>
</div>

templates/parts/edit/_specifications.html.twig
{% form_theme form with ['parts/edit/edit_form_styles.html.twig'] %}

{% import 'components/collection_type.macro.html.twig' as collection %}

<div {{ collection.controller(form.parameters, 'parameter.delete.confirm') }}>
    <table class="table table-striped table-sm table-bordered table-responsive-md" id="specifications_table" {{ collection.target() }}>
        <thead>
        <tr>
            <th>{% trans %}specifications.property{% endtrans %}</th>
            <th>{% trans %}specifications.symbol{% endtrans %}</th>
            <th>{% trans %}specifications.value_min{% endtrans %}</th>
            <th>{% trans %}specifications.value_typ{% endtrans %}</th>
            <th>{% trans %}specifications.value_max{% endtrans %}</th>
            <th>{% trans %}specifications.unit{% endtrans %}</th>
            <th>{% trans %}specifications.text{% endtrans %}</th>
            <th>{% trans %}specifications.group{% endtrans %}</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        {% for param in form.parameters %}
            {{ form_widget(param) }}
        {% endfor %}
        </tbody>
    </table>

    <button type="button" class="btn btn-success"  {% if not is_granted('edit', part) %}disabled{% endif %} {{ collection.create_btn() }}>
        <i class="fas fa-plus-square fa-fw"></i>
        {% trans %}specification.create{% endtrans %}
    </button>
</div>

templates/parts/edit/merge_parts.html.twig
{% extends "parts/edit/edit_part_info.html.twig" %}

{# @var merge_other \App\Entity\Parts\Part #}

{% block card_border %}border-info{% endblock %}
{% block card_type %}bg-info text-bg-info{% endblock %}

{% block title %}
    {% trans %}part.merge.title{% endtrans %} {{ merge_other.name }} {% trans %}part.merge.title.into{% endtrans %} {{ merge_old_name }}
{% endblock %}

{% block card_title %}
    <i class="fas fa-code-merge" aria-hidden="true"></i>
    {% trans %}part.merge.title{% endtrans %}
    <b><a class="text-bg-info" href="{{ entity_url(merge_other, 'info') }}">{{ merge_other.name }} (ID: {{ merge_other.iD }})</a></b>
    {% trans %}part.merge.title.into{% endtrans %}
    <b><a class="text-bg-info" href="{{ entity_url(part, 'info') }}">{{ merge_old_name }} (ID: {{ part.id }})</a></b>
{% endblock %}

{% block card_content %}
<div {{ stimulus_controller('elements/delete_btn') }} {{ stimulus_action('elements/delete_btn', "submit", "submit") }}
        data-delete-title="{% trans with {'%target%': merge_old_name|escape, '%other%': merge_other.name }%}part.merge.confirm.title{% endtrans %}"
        data-delete-message="{% trans with {'%other%': merge_other.name } %}part.merge.confirm.message{% endtrans %}">
    {{ parent() }}
</div>

{% endblock %}

templates/parts/edit/new_part.html.twig
{% extends "parts/edit/edit_part_info.html.twig" %}

{% block card_border %}border-success{% endblock %}
{% block card_type %}bg-success text-white{% endblock %}

{% block title %}
    {% trans %}part.new.card_title{% endtrans %}
{% endblock %}

{% block card_title %}
    <i class="fas fa-edit fa-plus-square" aria-hidden="true"></i>
    {% trans %}part.new.card_title{% endtrans %}
{% endblock %}

templates/parts/edit/update_from_ip.html.twig
{% extends "parts/edit/edit_part_info.html.twig" %}

{# @var merge_other \App\Entity\Parts\Part #}

{% block card_border %}border-info{% endblock %}
{% block card_type %}bg-info text-bg-info{% endblock %}

{% block before_card %}
    {% if bulk_job and jobId %}
        <div class="alert alert-info mb-3">
            <div class="d-flex justify-content-between align-items-center">
                <div>
                    <i class="fas fa-cloud-download fa-fw" aria-hidden="true"></i>
                    {% trans %}info_providers.bulk_import.editing_part{% endtrans %}
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}

{% block title %}
    {% trans %}info_providers.update_part.title{% endtrans %}: {{ merge_old_name }}
{% endblock %}

{% block card_title %}
    <i class="fas fa-cloud-arrow-down" aria-hidden="true"></i>
    {% trans %}info_providers.update_part.title{% endtrans %}:
    <b><a class="text-bg-info" href="{{ entity_url(part) }}">{{ merge_old_name }}</a></b>
{% endblock %}