src/Entity/DBElement.php
<?php

declare(strict_types=1);
/**
 * Part-DB Version 0.4+ "nextgen"
 * Copyright (C) 2016 - 2019 Jan Böhmer
 * https://github.com/jbtronics.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA
 */

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\DiscriminatorMap;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * This class is for managing all database objects.
 *
 * You should use this class for ALL classes which manages database records!
 *          (except special tables like "internal"...)
 * Every database table which are managed with this class (or a subclass of it)
 *          must have the table row "id"!! The ID is the unique key to identify the elements.
 *
 * @ORM\MappedSuperclass()
 *
 * @ORM\EntityListeners({"App\Security\EntityListeners\ElementPermissionListener"})
 *
 * @DiscriminatorMap(typeProperty="type", mapping={
 *      "attachment_type" = "App\Entity\AttachmentType",
 *      "attachment" = "App\Entity\Attachment",
 *      "category" = "App\Entity\Attachment",
 *      "device" = "App\Entity\Device",
 *      "device_part" = "App\Entity\DevicePart",
 *      "footprint" = "App\Entity\Footprint",
 *      "group" = "App\Entity\Group",
 *      "manufacturer" = "App\Entity\Manufacturer",
 *      "orderdetail" = "App\Entity\Orderdetail",
 *      "part" = "App\Entity\Part",
 *      "pricedetail" = "App\Entity\Pricedetail",
 *      "storelocation" = "App\Entity\Storelocation",
 *      "supplier" = "App\Entity\Supplier",
 *      "user" = "App\Entity\User"
 *  })
 */
abstract class DBElement
{
    /** @var int The Identification number for this part. This value is unique for the element in this table.
     * @ORM\Column(type="integer")
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @Groups({"full"})
     */
    protected $id;

    /**
     * Get the ID. The ID can be zero, or even negative (for virtual elements). If an elemenent is virtual, can be
     * checked with isVirtualElement().
     *
     * Returns null, if the element is not saved to the DB yet.
     *
     * @return int|null the ID of this element
     */
    final public function getID(): ?int
    {
        return $this->id;
    }

    /**
     * Returns the ID as an string, defined by the element class.
     * This should have a form like P000014, for a part with ID 14.
     *
     * @return string The ID as a string;
     *
     */
    abstract public function getIDString(): string;

    public function __clone()
    {
        //Set ID to null, so that an new entry is created
        $this->id = null;
    }
}

src/Controller/AssemblyController.php
<?php

declare(strict_types=1);

/*
 * This file is part of Part-DB (https://github.com/Part-DB/Part-DB-symfony).
 *
 *  Copyright (C) 2019 - 2022 Jan Böhmer (https://github.com/jbtronics)
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as published
 *  by the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
namespace App\Controller;

use App\DataTables\AssemblyBomEntriesDataTable;
use App\DataTables\AssemblyDataTable;
use App\DataTables\ErrorDataTable;
use App\DataTables\Filters\AssemblyFilter;
use App\Entity\AssemblySystem\Assembly;
use App\Entity\AssemblySystem\AssemblyBOMEntry;
use App\Entity\Parts\Part;
use App\Entity\UserSystem\User;
use App\Exceptions\InvalidRegexException;
use App\Form\AssemblySystem\AssemblyAddPartsType;
use App\Form\AssemblySystem\AssemblyBuildType;
use App\Form\Filters\AssemblyFilterType;
use App\Helpers\Assemblies\AssemblyBuildRequest;
use App\Services\ImportExportSystem\BOMImporter;
use App\Services\AssemblySystem\AssemblyBuildHelper;
use App\Services\Trees\NodesListBuilder;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\DBAL\Exception\DriverException;
use Doctrine\ORM\EntityManagerInterface;
use League\Csv\SyntaxError;
use Omines\DataTablesBundle\DataTableFactory;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Validator\Validator\ValidatorInterface;

use Symfony\Contracts\Translation\TranslatorInterface;
use function Symfony\Component\Translation\t;

#[Route(path: '/assembly')]
class AssemblyController extends AbstractController
{
    public function __construct(
        private readonly DataTableFactory $dataTableFactory,
        private readonly TranslatorInterface $translator,
        private readonly NodesListBuilder $nodesListBuilder
    ) {
    }

    #[Route(path: '/list', name: 'assemblies_list')]
    public function showAll(Request $request): Response
    {
        return $this->showListWithFilter($request,'assemblies/lists/all_list.html.twig');
    }

    /**
     * Common implementation for the part list pages.
     * @param  Request  $request The request to parse
     * @param  string  $template  The template that should be rendered
     * @param  callable|null  $filter_changer  A function that is called with the filter object as parameter. This function can be used to customize the filter
     * @param  callable|null  $form_changer  A function that is called with the form object as parameter. This function can be used to customize the form
     * @param  array  $additonal_template_vars  Any additional template variables that should be passed to the template
     * @param  array  $additional_table_vars Any additional variables that should be passed to the table creation
     */
    protected function showListWithFilter(Request $request, string $template, ?callable $filter_changer = null, ?callable $form_changer = null, array $additonal_template_vars = [], array $additional_table_vars = []): Response
    {
        $this->denyAccessUnlessGranted('@assemblies.read');

        $formRequest = clone $request;
        $formRequest->setMethod('GET');
        $filter = new AssemblyFilter($this->nodesListBuilder);
        if($filter_changer !== null){
            $filter_changer($filter);
        }

        $filterForm = $this->createForm(AssemblyFilterType::class, $filter, ['method' => 'GET']);
        if($form_changer !== null) {
            $form_changer($filterForm);
        }

        $filterForm->handleRequest($formRequest);

        $table = $this->dataTableFactory->createFromType(
            AssemblyDataTable::class,
            array_merge(['filter' => $filter], $additional_table_vars),
            ['lengthMenu' => AssemblyDataTable::LENGTH_MENU]
        )
            ->handleRequest($request);

        if ($table->isCallback()) {
            try {
                try {
                    return $table->getResponse();
                } catch (DriverException $driverException) {
                    if ($driverException->getCode() === 1139) {
                        //Convert the driver exception to InvalidRegexException so it has the same handler as for SQLite
                        throw InvalidRegexException::fromDriverException($driverException);
                    } else {
                        throw $driverException;
                    }
                }
            } catch (InvalidRegexException $exception) {
                $errors = $this->translator->trans('assembly.table.invalid_regex').': '.$exception->getReason();
                $request->request->set('order', []);

                return ErrorDataTable::errorTable($this->dataTableFactory, $request, $errors);
            }
        }

        return $this->render($template, array_merge([
            'datatable' => $table,
            'filterForm' => $filterForm->createView(),
        ], $additonal_template_vars));
    }

    #[Route(path: '/{id}/info', name: 'assembly_info', requirements: ['id' => '\d+'])]
    public function info(Assembly $assembly, Request $request, AssemblyBuildHelper $buildHelper): Response
    {
        $this->denyAccessUnlessGranted('read', $assembly);

        $table = $this->dataTableFactory->createFromType(AssemblyBomEntriesDataTable::class, ['assembly' => $assembly])
            ->handleRequest($request);

        if ($table->isCallback()) {
            return $table->getResponse();
        }

        return $this->render('assemblies/info/info.html.twig', [
            'buildHelper' => $buildHelper,
            'datatable' => $table,
            'assembly' => $assembly,
        ]);
    }

    #[Route(path: '/{id}/build', name: 'assembly_build', requirements: ['id' => '\d+'])]
    public function build(Assembly $assembly, Request $request, AssemblyBuildHelper $buildHelper, EntityManagerInterface $entityManager): Response
    {
        $this->denyAccessUnlessGranted('read', $assembly);

        //If no number of builds is given (or it is invalid), just assume 1
        $number_of_builds = $request->query->getInt('n', 1);
        if ($number_of_builds < 1) {
            $number_of_builds = 1;
        }

        $assemblyBuildRequest = new AssemblyBuildRequest($assembly, $number_of_builds);
        $form = $this->createForm(AssemblyBuildType::class, $assemblyBuildRequest);

        $form->handleRequest($request);
        if ($form->isSubmitted()) {
            if ($form->isValid()) {
                //Ensure that the user can withdraw stock from all parts
                $this->denyAccessUnlessGranted('@parts_stock.withdraw');

                //We have to do a flush already here, so that the newly created partLot gets an ID and can be logged to DB later.
                $entityManager->flush();
                $buildHelper->doBuild($assemblyBuildRequest);
                $entityManager->flush();
                $this->addFlash('success', 'assembly.build.flash.success');

                return $this->redirect(
                    $request->get('_redirect',
                        $this->generateUrl('assembly_info', ['id' => $assembly->getID()]
                        )));
            }

            $this->addFlash('error', 'assembly.build.flash.invalid_input');
        }

        return $this->render('assemblies/build/build.html.twig', [
            'buildHelper' => $buildHelper,
            'assembly' => $assembly,
            'build_request' => $assemblyBuildRequest,
            'number_of_builds' => $number_of_builds,
            'form' => $form,
        ]);
    }

    #[Route(path: '/{id}/import_bom', name: 'assembly_import_bom', requirements: ['id' => '\d+'])]
    public function importBOM(Request $request, EntityManagerInterface $entityManager, Assembly $assembly,
                              BOMImporter $BOMImporter, ValidatorInterface $validator): Response
    {
        $this->denyAccessUnlessGranted('edit', $assembly);

        $builder = $this->createFormBuilder();
        $builder->add('file', FileType::class, [
            'label' => 'import.file',
            'required' => true,
            'attr' => [
                'accept' => '.csv, .json'
            ]
        ]);
        $builder->add('type', ChoiceType::class, [
            'label' => 'assembly.bom_import.type',
            'required' => true,
            'choices' => [
                'assembly.bom_import.type.json' => 'json',
                'assembly.bom_import.type.csv' => 'csv',
                'assembly.bom_import.type.kicad_pcbnew' => 'kicad_pcbnew',
            ]
        ]);
        $builder->add('clear_existing_bom', CheckboxType::class, [
            'label' => 'assembly.bom_import.clear_existing_bom',
            'required' => false,
            'data' => false,
            'help' => 'assembly.bom_import.clear_existing_bom.help',
        ]);
        $builder->add('submit', SubmitType::class, [
            'label' => 'import.btn',
        ]);

        $form = $builder->getForm();

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {

templates/assemblies/info/_attachments_info.html.twig
{% import "helper.twig" as helper %}

<table class="table table-striped table-sm table-hover table-responsive-sm">
    <thead>
    <tr>
        <th></th>
        <th>{% trans %}attachment.name{% endtrans %}</th>
        <th>{% trans %}attachment.attachment_type{% endtrans %}</th>
        <th>{% trans %}attachment.file_name{% endtrans %}</th>
        <th>{% trans %}attachment.file_size{% endtrans %}</th>
        <th></th>
    </tr>
    </thead>

    <tbody>


    {% for attachment in assembly.attachments %}
        <tr>
            <td>
                {% import "components/attachments.macro.html.twig" as attachments %}
                {{ attachments.attachment_icon(attachment, attachment_manager) }}
            </td>
            <td class="align-middle">{{ attachment.name }}</td>
            <td class="align-middle">{{ attachment.attachmentType.fullPath }}</td>
            <td class="align-middle">
                {% if attachment.hasInternal() %}
                    {{ attachment.filename }}
                {% endif %}
            </td>
            <td class="align-middle h6">
                {% if not attachment.hasInternal() %}
                    <span class="badge bg-primary">
                            <i class="fas fa-fw fa-globe"></i> {% trans %}attachment.external_only{% endtrans %}
                        </span>
                {% elseif attachment_manager.internalFileExisting(attachment) %}
                    <span class="badge bg-secondary">
                        <i class="fas fa-hdd fa-fw"></i> {{ attachment_manager.humanFileSize(attachment) }}
                    </span>
                {% else %}
                    <span class="badge bg-warning">
                        <i class="fas fa-exclamation-circle fa-fw"></i> {% trans %}attachment.file_not_found{% endtrans %}
                    </span>
                {% endif %}
                {% if attachment.secure %}
                    <br><span class="badge bg-success">
                        <i class="fas fa-fw fa-shield-alt"></i> {% trans %}attachment.secure{% endtrans %}
                    </span>
                {% endif %}
                {% if attachment == assembly.masterPictureAttachment %}
                    <br>
                    <span class="badge bg-primary">
                        <i class="fas fa-id-card"></i> {% trans %}attachment.preview{% endtrans %}
                    </span>
                {% endif %}
            </td>

            <td><div class="btn-group" role="group" aria-label="">
                    <a {% if attachment.hasExternal() %}href="{{ attachment.externalPath }}"{% endif %} target="_blank"
                       class="btn btn-secondary {% if not attachment.hasExternal()  %}disabled{% endif %}"
                       data-turbo="false" title="{% trans with {"%host%": attachment.host} %}attachment.view_external.view_at{% endtrans %}" rel="noopener">
                        <i class="fas fa-globe fa-fw"></i>
                    </a>
                    <a {% if attachment_manager.isInternalFileExisting(attachment) %}href="{{ entity_url(attachment, 'file_view') }}"{% endif %} target="_blank"
                       class="btn btn-secondary {% if not attachment_manager.isInternalFileExisting(attachment) or (attachment.secure and not is_granted("show_private", attachment))  %}disabled{% endif %}"
                       data-turbo="false" title="{% trans %}attachment.view_local{% endtrans %}" rel="noopener">
                        <i class="fas fa-eye fa-fw"></i>
                    </a>
                    <a {% if attachment_manager.isInternalFileExisting(attachment)  %}href="{{ entity_url(attachment, 'file_download') }}"{% endif %} data-turbo="false"
                       class="btn btn-secondary {% if not attachment_manager.isInternalFileExisting(attachment) or (attachment.secure and not is_granted("show_private", attachment)) %}disabled{% endif %}"
                       title="{% trans %}attachment.download_local{% endtrans %}">
                        <i class="fas fa-download fa-fw"></i>
                    </a>

                    <div class="btn-group" role="group">
                        <button id="btnGroupDrop1" type="button" class="btn btn-secondary dropdown-toggle" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" data-boundary="window">
                        </button>
                        <div class="dropdown-menu" aria-labelledby="btnGroupDrop1">
                            <span class="text-muted dropdown-item-text" ><i class="fas fa-lightbulb fa-fw"></i> <b>ID:</b> {{ attachment.iD }}</span>
                            <span class="text-muted dropdown-item-text" ><i class="fas fa-history fa-fw"></i> <b>{% trans %}lastModified{% endtrans %}:</b> {{ helper.entity_last_modified(attachment) }}</span>
                            <span class="text-muted dropdown-item-text" ><i class="fas fa-calendar-plus fa-fw"></i> <b>{% trans %}createdAt{% endtrans %}:</b> {{ helper.entity_created_at(attachment) }}</span>

                        </div>
                    </div>
                </div></td>
        </tr>
    {% endfor %}

    </tbody>

</table>

templates/assemblies/info/_builds.html.twig
{% set can_build = buildHelper.assemblyBuildable(assembly) %}

{% import "components/assemblies.macro.html.twig" as assembly_macros %}

{% if assembly.status is not empty and assembly.status != "in_production" %}
    <div class="alert mt-2 alert-warning" role="alert">
        <i class="fa-solid fa-triangle-exclamation fa-fw"></i> {% trans with {"%assembly_status%": ('assembly.status.'~assembly.status)|trans } %}assembly.builds.check_assembly_status{% endtrans %}
    </div>
{% endif %}

<div class="alert mt-2 {% if can_build %}alert-success{% else %}alert-danger{% endif %}" role="alert">
    {% if not can_build %}
        <h5><i class="fa-solid fa-circle-exclamation fa-fw"></i> {% trans %}assembly.builds.build_not_possible{% endtrans %}</h5>
        <b>{% trans %}assembly.builds.following_bom_entries_miss_instock{% endtrans %}</b>
        <ul>
            {% for bom_entry in buildHelper.nonBuildableAssemblyBomEntries(assembly) %}
                <li>{{ assembly_macros.assembly_bom_entry_with_missing_instock(bom_entry) }}</li>
            {% endfor %}
        </ul>
    {% else %}
        <h5><i class="fa-solid fa-circle-check fa-fw"></i> {% trans %}assembly.builds.build_possible{% endtrans %}</h5>
        <span>{% trans with {"%max_builds%": buildHelper.maximumBuildableCount(assembly)} %}assembly.builds.number_of_builds_possible{% endtrans %}</span>
    {% endif %}
</div>

<form method="get" action="{{ path('assembly_build', {"id": assembly.iD }) }}">
    <div class="row mt-2">
        <div class="col-4">
            <div class="input-group mb-3">
                <input type="number" min="1" class="form-control" placeholder="{% trans %}assembly.builds.number_of_builds{% endtrans %}" name="n" required>
                <input type="hidden" name="_redirect" value="{{  uri_without_host(app.request) }}">
                <button class="btn btn-outline-secondary" type="submit" id="button-addon2">{% trans %}assembly.build.btn_build{% endtrans %}</button>
            </div>
        </div>
    </div>
</form>

{% if assembly.buildPart %}
    <p><b>{% trans %}assembly.builds.no_stocked_builds{% endtrans %}:</b> <a href="{{ entity_url(assembly.buildPart) }}">{{ assembly.buildPart.amountSum }}</a></p>
{% endif %}

templates/assemblies/info/_info.html.twig
{% import "helper.twig" as helper %}

<div class="row mt-2">
    <div class="col-md-8">
        <div class="row">
            <div class="col-md-3 col-lg-4 col-4 mt-auto mb-auto">
                {% if assembly.masterPictureAttachment %}
                    <a href="{{ entity_url(assembly.masterPictureAttachment, 'file_view') }}" data-turbo="false" target="_blank" rel="noopener">
                        <img class="d-block w-100 img-fluid img-thumbnail bg-body-tertiary part-info-image" src="{{ entity_url(assembly.masterPictureAttachment, 'file_view') }}" alt="">
                    </a>
                {% else %}
                    <img src="{{ asset('img/part_placeholder.svg') }}" class="img-fluid img-thumbnail bg-body-tertiary mb-2 " alt="Part main image" height="300" width="300">
                {% endif %}
            </div>
            <div class="col-md-9 col-lg-8 col-7">
                <h3 class="w-fit" title="{% trans %}name.label{% endtrans %}">{{ assembly.name }}
                    {# You need edit permission to use the edit button #}
                    {% if is_granted('edit', assembly) %}
                        <a href="{{ entity_url(assembly, 'edit') }}"><i class="fas fa-fw fa-sm fa-edit"></i></a>
                    {% endif %}
                </h3>
                <h6 class="text-muted w-fit" title="{% trans %}description.label{% endtrans %}"><span>{{ assembly.description|format_markdown(true) }}</span></h6>
                {% if assembly.buildPart %}
                    <h6>{% trans %}assembly.edit.associated_build_part{% endtrans %}:</h6>
                    <a href="{{ entity_url(assembly.buildPart) }}">{{ assembly.buildPart.name }}</a>
                {% endif %}

            </div>
        </div>
    </div>


    <div class="col-md-4"> {# Sidebar panel with infos about last creation date, etc. #}
        <div class="mb-3">
            <span class="text-muted" title="{% trans %}lastModified{% endtrans %}">
                <i class="fas fa-history fa-fw"></i>  {{ helper.date_user_combination(assembly, true) }}
            </span>
            <br>
            <span class="text-muted mt-1" title="{% trans %}createdAt{% endtrans %}">
                <i class="fas fa-calendar-plus fa-fw"></i> {{ helper.date_user_combination(assembly, false) }}
            </span>
        </div>

        <div class="mt-1">
            <h6>
                {{ helper.assemblies_status_to_badge(assembly.status) }}
            </h6>
        </div>
        <div class="mt-1">
            <h6>
                <span class="badge badge-primary bg-primary">
                    <i class="fa-solid fa-list-check fa-fw"></i>
                    {{ assembly.bomEntries | length }}
                    {% trans %}assembly.info.bom_entries_count{% endtrans %}
                </span>
            </h6>
        </div>
        {% if assembly.children is not empty %}
            <div class="mt-1">
                <h6>
                <span class="badge badge-primary bg-secondary">
                    <i class="fa-solid fa-folder-tree fa-fw"></i>
                    {{ assembly.children | length }}
                    {% trans %}assembly.info.sub_assemblies_count{% endtrans %}
                </span>
                </h6>
            </div>
        {% endif %}
    </div>

    {% if assembly.comment is not empty %}
        <p>
        <h5>{% trans %}comment.label{% endtrans %}:</h5>
        {{ assembly.comment|format_markdown }}
        </p>
    {% endif %}
</div>

templates/assemblies/info/_part.html.twig
{% import "components/datatables.macro.html.twig" as datatables %}

<div class="mb-2 mt-2"></div>

{{ datatables.datatable(datatable, 'elements/datatables/datatables', 'assemblies') }}

templates/assemblies/info/info.html.twig
{% extends "main_card.html.twig" %}
{% import "helper.twig" as helper %}

{% block  title %}
    {% trans %}assembly.info.title{% endtrans %}: {{ assembly.name }}
{% endblock %}

{% block before_card %}
    <div class="row mb-3">
        <div class="col d-flex align-items-center">
            <a href="{{ path('assembly_new') }}"
               class="btn btn-success me-2 {% if not is_granted('@assemblies.create') %}disabled{% endif %}">
                <i class="fas fa-plus-square fa-fw"></i>
                {% trans %}assembly.new{% endtrans %}
            </a>

            <div class="btn-group">
                <a class="btn btn-success" {% if not is_granted('@assemblies.edit') %}disabled{% endif %}
                   href="{{ path('assembly_add_parts', {"id": assembly.id, "_redirect":  uri_without_host(app.request)}) }}">
                    <i class="fa-solid fa-square-plus fa-fw"></i>
                    {% trans %}assembly.info.bom_add_parts{% endtrans %}
                </a>
                <button type="button" class="btn btn-success dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown" aria-expanded="false">
                    <span class="visually-hidden">Toggle Dropdown</span>
                </button>
                <ul class="dropdown-menu">
                    <li>
                        <a class="dropdown-item" href="{{ path('assembly_import_bom', {'id': assembly.id}) }}" {% if not is_granted('edit', assembly) %}disabled="disabled"{% endif %}>
                            <i class="fa-solid fa-file-import fa-fw"></i>
                            {% trans %}assembly.edit.bom.import_bom{% endtrans %}
                        </a>
                    </li>
                </ul>
            </div>

            <a class="btn btn-secondary ms-2" {% if not is_granted('@assemblies.edit') %}disabled{% endif %}
               href="{{ path('assembly_edit', {"id": assembly.id}) }}#part">
                <i class="fa-solid fa-square-plus fa-cog"></i>
                {% trans %}assembly_bom_entry.label{% endtrans %}
            </a>

            <a class="btn btn-secondary ms-2" {% if not is_granted('@assemblies.edit') %}disabled{% endif %}
               href="{{ path('assembly_edit', {"id": assembly.id}) }}">
                <i class="fa-solid fa-pencil"></i>
            </a>
        </div>
    </div>
{% endblock %}

{% block content %}
    {{ helper.breadcrumb_entity_link(assembly) }}
    {{ parent() }}
{% endblock %}

{% block card_title %}
    {% if assembly.masterPictureAttachment is not null and attachment_manager.isFileExisting(assembly.masterPictureAttachment) %}
        <img class="hoverpic ms-0 me-1 d-inline" {{ stimulus_controller('elements/hoverpic') }} data-thumbnail="{{ entity_url(assembly.masterPictureAttachment, 'file_view') }}" src="{{ attachment_thumbnail(assembly.masterPictureAttachment, 'thumbnail_sm') }}">
    {% else %}
        {{ helper.entity_icon(assembly, "me-1") }}
    {% endif %}
    {% trans %}assembly.info.title{% endtrans %}:&nbsp;<b>{{ assembly.name }}</b>
{% endblock %}

{% block card_content %}
    <ul class="nav nav-tabs" role="tablist">
        <li class="nav-item" role="presentation">
            <button class="nav-link active" id="info-tab" data-bs-toggle="tab" data-bs-target="#info-tab-pane"
                    type="button" role="tab" aria-controls="info-tab-pane" aria-selected="true">
                <i class="fa-solid fa-circle-info fa-fw"></i>
                {% trans %}assembly.info.info.label{% endtrans %}
            </button>
        </li>
        <li class="nav-item" role="presentation">
            <button class="nav-link" id="part-tab" data-bs-toggle="tab" data-bs-target="#part-tab-pane"
                    type="button" role="tab" aria-controls="part-tab-pane" aria-selected="false">
                <i class="fa-solid fa-list-check fa-fw"></i>
                {% trans %}assembly_bom_entry.label{% endtrans %}
                <span class="badge bg-secondary">{{ assembly.bomEntries | length }}</span>
            </button>
        </li>
        <li class="nav-item" role="presentation">
            <button class="nav-link" id="builds-tab" data-bs-toggle="tab" data-bs-target="#builds-tab-pane"
                    type="button" role="tab" aria-controls="builds-tab-pane" aria-selected="false">
                <i class="fa-solid fa-bolt fa-fw"></i>
                {% trans %}assembly.info.builds.label{% endtrans %}
            </button>
        </li>
        {% if assembly.attachments is not empty %}
            <li class="nav-item">
                <a class="nav-link" id="attachments-tab" data-bs-toggle="tab"
                   data-bs-target="#attachments-tab-pane" role="tab">
                    <i class="fas fa-paperclip fa-fw"></i>
                    {% trans %}attachment.labelp{% endtrans %}
                    <span class="badge bg-secondary">{{ assembly.attachments | length }}</span>
                </a>
            </li>
        {% endif %}
    </ul>

    <div class="tab-content">
        <div class="tab-pane fade show active" id="info-tab-pane" role="tabpanel" aria-labelledby="info-tab" tabindex="0">
            {% include "assemblies/info/_info.html.twig" %}
        </div>
        <div class="tab-pane fade" id="part-tab-pane" role="tabpanel" aria-labelledby="part-tab" tabindex="0">
            {% include "assemblies/info/_part.html.twig" %}
        </div>
        <div class="tab-pane fade" id="builds-tab-pane" role="tabpanel" aria-labelledby="builds-tab" tabindex="0">
            {% include "assemblies/info/_builds.html.twig" %}
        </div>
        <div class="tab-pane fade" id="attachments-tab-pane" role="tabpanel" aria-labelledby="attachments-tab" tabindex="0">
            {% include "assemblies/info/_attachments_info.html.twig" with {"assembly": assembly} %}
        </div>
    </div>

{% endblock %}