src/Entity/Part.php
<?php

declare(strict_types=1);

/**
 * part-db version 0.1
 * Copyright (C) 2005 Christoph Lechner
 * http://www.cl-projects.de/.
 *
 * part-db version 0.2+
 * Copyright (C) 2009 K. Jacobs and others (see authors.php)
 * http://code.google.com/p/part-db/
 *
 * Part-DB Version 0.4+
 * Copyright (C) 2016 - 2019 Jan Böhmer
 * https://github.com/jbtronics
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA
 */

namespace App\Entity;

use App\Security\Annotations\ColumnSecurity;
use Doctrine\ORM\Mapping as ORM;
//use Webmozart\Assert\Assert;

use Symfony\Component\Validator\Constraints as Assert;

/**
 * Class Part.
 *
 * @ORM\Entity(repositoryClass="App\Repository\PartRepository")
 * @ORM\Table("`parts`")
 */
class Part extends AttachmentContainingDBElement
{
    public const INSTOCK_UNKNOWN = -2;

    /**
     * @ORM\OneToMany(targetEntity="PartAttachment", mappedBy="element")
     */
    protected $attachments;

    /**
     * @var Category
     * @ORM\ManyToOne(targetEntity="Category", inversedBy="parts")
     * @ORM\JoinColumn(name="id_category", referencedColumnName="id")
     */
    protected $category;

    /**
     * @var Footprint|null
     * @ORM\ManyToOne(targetEntity="Footprint", inversedBy="parts")
     * @ORM\JoinColumn(name="id_footprint", referencedColumnName="id")
     *
     * @ColumnSecurity(prefix="footprint", type="object")
     */
    protected $footprint;

    /**
     * @var Storelocation|null
     * @ORM\ManyToOne(targetEntity="Storelocation", inversedBy="parts")
     * @ORM\JoinColumn(name="id_storelocation", referencedColumnName="id")
     *
     * @ColumnSecurity(prefix="storelocation", type="object")
     */
    protected $storelocation;

    /**
     * @var Manufacturer|null
     * @ORM\ManyToOne(targetEntity="Manufacturer", inversedBy="parts")
     * @ORM\JoinColumn(name="id_manufacturer", referencedColumnName="id")
     *
     * @ColumnSecurity(prefix="manufacturer", type="object")
     */
    protected $manufacturer;

    /**
     * @var Attachment
     * @ORM\ManyToOne(targetEntity="Attachment")
     * @ORM\JoinColumn(name="id_master_picture_attachement", referencedColumnName="id")
     *
     * @ColumnSecurity(prefix="attachments", type="object")
     */
    protected $master_picture_attachment;

    /**
     * @var Orderdetail[]
     * @ORM\OneToMany(targetEntity="Orderdetail", mappedBy="part")
     *
     * @ColumnSecurity(prefix="orderdetails", type="object")
     */
    protected $orderdetails;

    /**
     * @var Orderdetail
     * @ORM\OneToOne(targetEntity="Orderdetail")
     * @ORM\JoinColumn(name="order_orderdetails_id", referencedColumnName="id")
     *
     * @ColumnSecurity(prefix="order", type="object")
     */
    protected $order_orderdetail;

    //TODO
    protected $devices;

    /**
     *  @ColumnSecurity(type="datetime")
     *  @ORM\Column(type="datetimetz", name="datetime_added")
     */
    protected $addedDate;

    /**
     * @var \DateTime The date when this element was modified the last time.
     * @ORM\Column(type="datetimetz", name="last_modified")
     * @ColumnSecurity(type="datetime")
     */
    protected $lastModified;

    /**********************
     * Propertys
     ***********************/

    /**
     * @var string
     * @ORM\Column(type="string")
     *
     * @ColumnSecurity(prefix="name")
     */
    protected $name;

    /**
     * @var string
     * @ORM\Column(type="text")
     *
     * @ColumnSecurity(prefix="description")
     */
    protected $description = '';

    /**
     * @var int
     * @ORM\Column(type="integer")
     * @Assert\GreaterThanOrEqual(0)
     *
     * @ColumnSecurity(prefix="instock", type="integer")
     */
    protected $instock = 0;

    /**
     * @var int
     * @ORM\Column(type="integer")
     * @Assert\GreaterThanOrEqual(0)
     *
     * @ColumnSecurity(prefix="mininstock", type="integer")
     */
    protected $mininstock = 0;

    /**
     * @var string
     * @ORM\Column(type="text")
     * @ColumnSecurity(prefix="comment")
     */
    protected $comment = '';

    /**
     * @var bool
     * @ORM\Column(type="boolean")
     */
    protected $visible = true;

    /**
     * @var bool
     * @ORM\Column(type="boolean")
     * @ColumnSecurity(type="boolean")
     */
    protected $favorite = false;

    /**
     * @var int
     * @ORM\Column(type="integer")
     * @ColumnSecurity(prefix="order", type="integer")
     */
    protected $order_quantity = 0;

    /**
     * @var bool
     * @ORM\Column(type="boolean")
     * @ColumnSecurity(prefix="order", type="boolean")
     */
    protected $manual_order = false;

    /**
     * @var string
     * @ORM\Column(type="string")
     *@ColumnSecurity(prefix="manufacturer", type="string", placeholder="")
     */
    protected $manufacturer_product_url = '';

    /**
     * Returns the ID as an string, defined by the element class.
     * This should have a form like P000014, for a part with ID 14.
     *
     * @return string The ID as a string;
     */
    public function getIDString(): string
    {
        return 'P'.sprintf('%06d', $this->getID());
    }

    /*********************************************************************************
     * Getters
     ********************************************************************************/

    /**
     * Get the description string like it is saved in the database.
     * This can contain BBCode, it is not parsed yet.
     *
     * @return string the description
     */
    public function getDescription(): string
    {
        return  htmlspecialchars($this->description);
    }

    /**
     *  Get the count of parts which are in stock.
     *  When the instock is unkown, then Part::INSTOCK_UNKNOWN is returned.
     *
     * @return int count of parts which are in stock
     */
    public function getInstock(): int
    {
        return $this->instock;
    }

    /**
     * Check if the value of the Instock is unknown.
     *
     * @return bool True, if the value of the instock is unknown.
     */
    public function isInstockUnknown(): bool
    {
        return $this->instock <= static::INSTOCK_UNKNOWN;
    }

    /** @noinspection ReturnTypeCanBeDeclaredInspection */

    /**
     *  Get the count of parts which must be in stock at least.
     *
     * @return int count of parts which must be in stock at least
     */
    public function getMinInstock(): int
    {
        return $this->mininstock;
    }

    /**
     *  Get the comment associated with this part.
     *
     * @return string The raw/unparsed comment
     */
    public function getComment(): string
    {
        return htmlspecialchars($this->comment);
    }

    /**
     *  Get if this part is obsolete.
     *
     *     A Part is marked as "obsolete" if all their orderdetails are marked as "obsolete".
     *          If a part has no orderdetails, the part isn't marked as obsolete.
     *
     * @return bool true, if this part is obsolete. false, if this part isn't obsolete
     */
    public function isObsolete(): bool
    {
        $all_orderdetails = $this->getOrderdetails();

        if (0 === count($all_orderdetails)) {
            return false;
        }

        foreach ($all_orderdetails as $orderdetails) {
            if (!$orderdetails->getObsolete()) {
                return false;
            }
        }

        return true;
    }

    /**
     *  Get if this part is visible.
     *
     * @return bool true if this part is visible
     *              false if this part isn't visible
     */
    public function isVisible(): bool
    {
        return $this->visible;
    }

    /**
     * Get if this part is a favorite.
     *
     * @return bool * true if this part is a favorite
     *              * false if this part is not a favorite.
     */
    public function isFavorite(): bool
    {
        return $this->favorite;
    }

    /**
     *  Get the selected order orderdetails of this part.
     *
     * @return Orderdetail the selected order orderdetails
     *
     * @throws Exception
     */
    public function getOrderOrderdetails(): ?Orderdetail
    {
        //TODO
        /*
        if ($this->order_orderdetails->getObsolete()) {
            $this->setOrderOrderdetailsID(null);
            $this->order_orderdetails = null;
        }*/

        return $this->order_orderdetail;
    }

    /**
     *  Get the order quantity of this part.
     *
     * @return int the order quantity
     */
    public function getOrderQuantity(): int
    {
        return $this->order_quantity;
    }

    /**
     *  Get the minimum quantity which should be ordered.
     *
     * @param bool $with_devices * if true, all parts from devices which are marked as "to order" will be included in the calculation
     *                           * if false, only max(mininstock - instock, 0) will be returned
     *
     * @return int the minimum order quantity
     *
     * @throws Exception
     */
    public function getMinOrderQuantity(bool $with_devices = true): int
    {
        //TODO
        throw new \Exception('Not implemented yet...');
        /*
        if ($with_devices) {
        $count_must_order = 0;      // for devices with "order_only_missing_parts == false"
        $count_should_order = 0;    // for devices with "order_only_missing_parts == true"

src/Entity/Parts/Footprint.php
<?php
/**
 * This file is part of Part-DB (https://github.com/Part-DB/Part-DB-symfony).
 *
 * Copyright (C) 2019 - 2022 Jan Böhmer (https://github.com/jbtronics)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

declare(strict_types=1);

namespace App\Entity\Parts;

use Doctrine\Common\Collections\Criteria;
use ApiPlatform\Doctrine\Common\Filter\DateFilterInterface;
use ApiPlatform\Doctrine\Orm\Filter\DateFilter;
use ApiPlatform\Doctrine\Orm\Filter\OrderFilter;
use ApiPlatform\Metadata\ApiFilter;
use ApiPlatform\Metadata\ApiProperty;
use ApiPlatform\Metadata\ApiResource;
use ApiPlatform\Metadata\Delete;
use ApiPlatform\Metadata\Get;
use ApiPlatform\Metadata\GetCollection;
use ApiPlatform\Metadata\Link;
use ApiPlatform\Metadata\Patch;
use ApiPlatform\Metadata\Post;
use ApiPlatform\OpenApi\Model\Operation;
use ApiPlatform\Serializer\Filter\PropertyFilter;
use App\ApiPlatform\Filter\LikeFilter;
use App\Entity\Attachments\Attachment;
use App\Entity\EDA\EDAFootprintInfo;
use App\Repository\Parts\FootprintRepository;
use App\Entity\Base\AbstractStructuralDBElement;
use Doctrine\Common\Collections\ArrayCollection;
use App\Entity\Attachments\FootprintAttachment;
use App\Entity\Base\AbstractPartsContainingDBElement;
use App\Entity\Parameters\FootprintParameter;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * This entity represents a footprint of a part (its physical dimensions and shape).
 *
 * @extends AbstractPartsContainingDBElement<FootprintAttachment, FootprintParameter>
 */
#[ORM\Entity(repositoryClass: FootprintRepository::class)]
#[ORM\Table('`footprints`')]
#[ORM\Index(columns: ['name'], name: 'footprint_idx_name')]
#[ORM\Index(columns: ['parent_id', 'name'], name: 'footprint_idx_parent_name')]
#[ApiResource(
    operations: [
        new Get(security: 'is_granted("read", object)'),
        new GetCollection(security: 'is_granted("@footprints.read")'),
        new Post(securityPostDenormalize: 'is_granted("create", object)'),
        new Patch(security: 'is_granted("edit", object)'),
        new Delete(security: 'is_granted("delete", object)'),
    ],
    normalizationContext: ['groups' => ['footprint:read', 'api:basic:read'], 'openapi_definition_name' => 'Read'],
    denormalizationContext: ['groups' => ['footprint:write', 'api:basic:write', 'attachment:write', 'parameter:write'], 'openapi_definition_name' => 'Write'],
)]
#[ApiResource(
    uriTemplate: '/footprints/{id}/children.{_format}',
    operations: [
        new GetCollection(
            openapi: new Operation(summary: 'Retrieves the children elements of a footprint.'),
            security: 'is_granted("@footprints.read")'
        )
    ],
    uriVariables: [
        'id' => new Link(fromProperty: 'children', fromClass: Footprint::class)
    ],
    normalizationContext: ['groups' => ['footprint:read', 'api:basic:read'], 'openapi_definition_name' => 'Read']
)]
#[ApiFilter(PropertyFilter::class)]
#[ApiFilter(LikeFilter::class, properties: ["name", "comment"])]
#[ApiFilter(DateFilter::class, strategy: DateFilterInterface::EXCLUDE_NULL)]
#[ApiFilter(OrderFilter::class, properties: ['name', 'id', 'addedDate', 'lastModified'])]
class Footprint extends AbstractPartsContainingDBElement
{
    #[ORM\ManyToOne(targetEntity: self::class, inversedBy: 'children')]
    #[ORM\JoinColumn(name: 'parent_id')]
    #[Groups(['footprint:read', 'footprint:write'])]
    #[ApiProperty(readableLink: false, writableLink: false)]
    protected ?AbstractStructuralDBElement $parent = null;

    #[ORM\OneToMany(mappedBy: 'parent', targetEntity: self::class)]
    #[ORM\OrderBy(['name' => Criteria::ASC])]
    protected Collection $children;

    #[Groups(['footprint:read', 'footprint:write'])]
    protected string $comment = '';

    /**
     * @var Collection<int, FootprintAttachment>
     */
    #[Assert\Valid]
    #[ORM\OneToMany(mappedBy: 'element', targetEntity: FootprintAttachment::class, cascade: ['persist', 'remove'], orphanRemoval: true)]
    #[ORM\OrderBy(['name' => Criteria::ASC])]
    #[Groups(['footprint:read', 'footprint:write'])]
    protected Collection $attachments;

    #[ORM\ManyToOne(targetEntity: FootprintAttachment::class)]
    #[ORM\JoinColumn(name: 'id_preview_attachment', onDelete: 'SET NULL')]
    #[Groups(['footprint:read', 'footprint:write'])]
    protected ?Attachment $master_picture_attachment = null;

    /**
     * @var FootprintAttachment|null
     */
    #[ORM\ManyToOne(targetEntity: FootprintAttachment::class)]
    #[ORM\JoinColumn(name: 'id_footprint_3d')]
    #[Groups(['footprint:read', 'footprint:write'])]
    protected ?FootprintAttachment $footprint_3d = null;

    /** @var Collection<int, FootprintParameter>
     */
    #[Assert\Valid]
    #[ORM\OneToMany(mappedBy: 'element', targetEntity: FootprintParameter::class, cascade: ['persist', 'remove'], orphanRemoval: true)]
    #[ORM\OrderBy(['group' => Criteria::ASC, 'name' => 'ASC'])]
    #[Groups(['footprint:read', 'footprint:write'])]
    protected Collection $parameters;

    #[Groups(['footprint:read'])]
    protected ?\DateTimeImmutable $addedDate = null;
    #[Groups(['footprint:read'])]
    protected ?\DateTimeImmutable $lastModified = null;

    #[Assert\Valid]
    #[ORM\Embedded(class: EDAFootprintInfo::class)]
    #[Groups(['full', 'footprint:read', 'footprint:write'])]
    protected EDAFootprintInfo $eda_info;

    public function __construct()
    {
        parent::__construct();
        $this->children = new ArrayCollection();
        $this->attachments = new ArrayCollection();
        $this->parameters = new ArrayCollection();
        $this->eda_info = new EDAFootprintInfo();
    }

    /****************************************
     * Getters
     ****************************************/

    /**
     * Returns the 3D Model associated with this footprint.
     */
    public function getFootprint3d(): ?FootprintAttachment
    {
        return $this->footprint_3d;
    }

    /********************************************************************************
     *
     *   Setters
     *
     *********************************************************************************/
    /**
     * Sets the 3D Model associated with this footprint.
     *
     * @param FootprintAttachment|null $new_attachment The new 3D Model
     */
    public function setFootprint3d(?FootprintAttachment $new_attachment): self
    {
        $this->footprint_3d = $new_attachment;

        return $this;
    }

    public function getEdaInfo(): EDAFootprintInfo
    {
        return $this->eda_info;
    }

    public function setEdaInfo(EDAFootprintInfo $eda_info): Footprint
    {
        $this->eda_info = $eda_info;
        return $this;
    }
}

templates/parts/info/_extended_infos.html.twig
{% import "helper.twig" as helper %}

<table class="table table-striped table-hover table-sm w-100 table-responsive-sm">
    <tbody>
    <tr> {# Creation date #}
        <td>{% trans %}createdAt{% endtrans %}</td>
        <td>{{ part.addedDate | format_datetime("long")}}</td>
    </tr>

    <tr>
        <td>{% trans %}user.creating_user{% endtrans %}</td>
        <td>{% if is_granted('show_history', part) %}
                {{ creating_user(part).fullName(true) ?? 'Unknown'|trans }}
            {% else %}
                {% trans %}accessDenied{% endtrans %}
            {% endif %}
        </td>
    </tr>

    <tr> {# Last modified date #}
        <td>{% trans %}lastModified{% endtrans %}</td>
        <td>{{ part.lastModified | format_datetime("long")}}</td>
    </tr>

    <tr>
        <td>{% trans %}user.last_editing_user{% endtrans %}</td>
        <td>{% if is_granted('show_history', part) %}
                {{ last_editing_user(part).fullName(true) ?? 'Unknown'|trans }}
            {% else %}
                {% trans %}accessDenied{% endtrans %}
            {% endif %}
        </td>
    </tr>

    <tr> {# ID #}
        <td>{% trans %}id.label{% endtrans %}</td>
        <td>{{ part.iD }}</td>
    </tr>

    <tr> {# IPN #}
        <td>{% trans %}part.edit.ipn{% endtrans %}</td>
        <td>{{ part.ipn ?? 'part.ipn.not_defined'|trans }}</td>
    </tr>

    <tr> {# Favorite status #}
        <td>{% trans %}part.isFavorite{% endtrans %}</td>
        <td>{{ helper.boolean_badge(part.favorite) }}</td>
    </tr>

    <tr> {# Build status #}
        <td>{% trans %}part.is_build_part{% endtrans %}</td>
        <td>{{ helper.boolean_badge(part.projectBuildPart) }}
            {% if part.projectBuildPart %}(<a href="{{ entity_url(part.builtProject, "edit") }}">{{ part.builtProject.name }}</a>){% endif %}</td>
    </tr>

    <tr>
        <td>{% trans %}part.minOrderAmount{% endtrans %}</td>
        <td>{% if  pricedetail_helper.minOrderAmount(part) %}
                {{ pricedetail_helper.minOrderAmount(part) | format_amount(part.partUnit) }}
            {% else %}
                {% trans %}Unknown{% endtrans %}
            {% endif %}
        </td>
    </tr>

    <tr>
        <td>{% trans %}part.info_provider_reference{% endtrans %}</td>
        <td>
            {% if part.providerReference.providerCreated %}
                {% if part.providerReference.providerUrl %}
                    <a href="{{ part.providerReference.providerUrl }}" rel="noopener">
                {% endif %}
                <span title="{{ part.providerReference.providerKey }}">{{ info_provider_label(part.providerReference.providerKey)|default(part.providerReference.providerKey) }}</span>: {{ part.providerReference.providerId }}
                <span> ({{ part.providerReference.lastUpdated | format_datetime() }})</span>
                {% if part.providerReference.providerUrl %}
                    </a>
                {% endif %}

                {# Show last updated date #}

            {% else %}
                {{ helper.boolean_badge(part.providerReference.providerCreated) }}
            {% endif %}

        </td>
    </tr>

    <tr>
        <td>{% trans %}part.edit.tab.eda{% endtrans %}</td>
        <td>
            <b>{% trans %}eda_info.reference_prefix{% endtrans %}:</b> {{ part.edaInfo.referencePrefix ?? part.category.edaInfo.referencePrefix ?? "" }}
            <br>
            <b>{% trans %}eda_info.value{% endtrans %}:</b> {{ part.edaInfo.value }}
            <br>
            <b>{% trans %}eda_info.visibility{% endtrans %}:</b> {{ helper.boolean_badge( part.edaInfo.visibility ?? part.category.edaInfo.visibility) }}
            <br>
            <b>{% trans %}eda_info.exclude_from_bom{% endtrans %}:</b> {{ helper.boolean_badge( part.edaInfo.excludeFromBom ?? part.category.edaInfo.excludeFromBom ?? false) }}
            <br>
            <b>{% trans %}eda_info.exclude_from_board{% endtrans %}:</b> {{ helper.boolean_badge( part.edaInfo.excludeFromBoard ?? part.category.edaInfo.excludeFromBoard ?? false) }}
            <br>
            <b>{% trans %}eda_info.exclude_from_sim{% endtrans %}:</b> {{ helper.boolean_badge( part.edaInfo.excludeFromSim ?? part.category.edaInfo.excludeFromSim ?? false) }}
            <br>
            <b>{% trans %}eda_info.kicad_symbol{% endtrans %}:</b> {{ part.edaInfo.kicadSymbol ?? part.category.edaInfo.kicadSymbol ?? "" }}
            <br>
            <b>{% trans %}eda_info.kicad_footprint{% endtrans %}:</b> {{ part.edaInfo.kicadFootprint ?? part.footprint.edaInfo.kicadFootprint ?? "" }}
        </td>
    </tr>
    </tbody>
</table>

templates/parts/info/_history.html.twig
<div class="mt-2">
    {% if datatable is not null %}
        {% import "components/history_log_macros.html.twig" as log %}
        {{ log.element_history_component(datatable) }}
    {% endif %}
</div>

templates/parts/info/_withdraw_modal.html.twig
<div class="modal fade" id="withdraw-modal" tabindex="-1" aria-labelledby="withdraw-modal-title" aria-hidden="true" {{ stimulus_controller('pages/part_withdraw_modal') }}>
    <form method="post" action="{{ path('part_add_withdraw', {"id": part.id}) }}">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="withdraw-modal-title"
                        data-withdraw="{% trans %}part.info.withdraw_modal.title.withdraw{% endtrans %}"
                        data-add="{% trans %}part.info.withdraw_modal.title.add{% endtrans %}"
                        data-move="{% trans %}part.info.withdraw_modal.title.move{% endtrans %}"
                    >Filled by JS Controller</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    {# non visible form elements #}
                    <input type="hidden" name="lot_id" value="">
                    <input type="hidden" name="action" value="">
                    <input type="hidden" name="_csfr" value="{{ csrf_token('part_withraw' ~ part.iD) }}">
                    <input type="hidden" name="_redirect" value="{{  uri_without_host(app.request) }}">

                    <div class="row mb-2">
                        <label class="col-form-label col-sm-3">
                            {% trans %}part.info.withdraw_modal.amount{% endtrans %}
                        </label>
                        <div class="col-sm-9">
                            <input type="number" required class="form-control" min="0" step="{{ (part.partUnit and not part.partUnit.integer) ? 'any' : '1' }}" name="amount" value="">
                        </div>
                    </div>

                    <div class="row mb-2 d-none" id="withdraw-modal-move-to">
                        <label class="col-form-label col-sm-3">{% trans %}part.info.withdraw_modal.move_to{% endtrans %}</label>
                        <div class="col-sm-9">
                            {% for lots in part.partLots|filter(l => l.instockUnknown == false) %}

                                <div class="form-check">
                                    <input class="form-check-input" type="radio" name="target_id" value="{{ lots.iD }}" id="modal_target_radio_{{ lots.iD }}" {% if not withdraw_add_helper.canAdd(lots) %}disabled{% endif %} required {% if loop.first %}checked{% endif %}>
                                    <label class="form-check-label" for="modal_target_radio_{{ lots.iD }}">
                                        {{ (lots.storageLocation) ? lots.storageLocation.fullPath : ("Lot " ~ loop.index) }}{% if lots.name is not empty %} ({{ lots.name }}){% endif %}: <b>{{ lots.amount | format_amount(part.partUnit) }}</b>
                                    </label>
                                </div>
                            {% endfor %}
                        </div>
                    </div>

                    <div class="row mb-2">
                        <label class="col-form-label col-sm-3">
                            {% trans %}part.info.withdraw_modal.comment{% endtrans %}
                        </label>
                        <div class="col-sm-9">
                            <input type="text" class="form-control" name="comment" value="" {% if event_comment_needed('part_stock_operation') %}required{% endif %}>
                            <div id="emailHelp" class="form-text">{% trans %}part.info.withdraw_modal.comment.hint{% endtrans %}</div>
                        </div>
                    </div>

                    <div class="row mb-2">
                        <label class="col-form-label col-sm-3">
                            {% trans %}part.info.withdraw_modal.timestamp{% endtrans %}
                        </label>
                        <div class="col-sm-9">
                            {# The timestamp must be between a year ago and 1 hour in the future #}
                            <input type="datetime-local" class="form-control" name="timestamp" value=""
                                   max="{{ "+10mins"|date('Y-m-d\\TH:i') }}" min="{{ "-1year"|date('Y-m-d\\TH:i') }}">
                            <div id="emailHelp" class="form-text">{% trans %}part.info.withdraw_modal.timestamp.hint{% endtrans %}</div>
                        </div>
                    </div>

                    <div class="row mb-2">
                        <div class="col-sm-9 offset-sm-3">
                            {# The timestamp must be between a year ago and 1 hour in the future #}
                            <div class="form-check">
                                <input class="form-check-input" type="checkbox" name="delete_lot_if_empty" value="true" id="withdraw_modal_delete_if_empty">
                                <label class="form-check-label" for="withdraw_modal_delete_if_empty">
                                    {% trans %}part.info.withdraw_modal.delete_lot_if_empty{% endtrans %}
                                </label>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">{% trans %}modal.close{% endtrans %}</button>
                    <button type="submit" class="btn btn-primary">{% trans %}modal.submit{% endtrans %}</button>
                </div>
            </div>
        </div>
    </form>
</div>